version: "3.9"

services:

  mariadb:
    image: mariadb:11
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=rootpass
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/99-init.sql:ro
    ports:
      - "3306:3306"

  vault:
    image: hashicorp/vault:1.16
    restart: unless-stopped
    environment:
      # mode DEV pour la démo ; en prod configure un storage backend + TLS
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"

  app:
    build: ./app
    depends_on:
      - mariadb
      - vault
    environment:
      # l’URL et le token Vault sont ici pour la démo
      VAULT_ADDR: "http://vault:8200"
      VAULT_TOKEN: "root"
      PORT: "3000"
    ports:
      - "3000:3000"

volumes:
  db_data:
